[2022-06-12 16:59:43,518] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.save_data_task scheduled__2022-06-12T03:06:00+00:00 [queued]>
[2022-06-12 16:59:43,553] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.save_data_task scheduled__2022-06-12T03:06:00+00:00 [queued]>
[2022-06-12 16:59:43,554] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 16:59:43,554] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-12 16:59:43,555] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 16:59:43,638] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): save_data_task> on 2022-06-12 03:06:00+00:00
[2022-06-12 16:59:43,644] {standard_task_runner.py:52} INFO - Started process 6525 to run task
[2022-06-12 16:59:43,652] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_data', 'save_data_task', 'scheduled__2022-06-12T03:06:00+00:00', '--job-id', '767', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmp2a824fej', '--error-file', '/tmp/tmp05ravvue']
[2022-06-12 16:59:43,654] {standard_task_runner.py:80} INFO - Job 767: Subtask save_data_task
[2022-06-12 16:59:43,784] {task_command.py:370} INFO - Running <TaskInstance: ingest_data.save_data_task scheduled__2022-06-12T03:06:00+00:00 [running]> on host DESKTOP-GDPK8BL.localdomain
[2022-06-12 16:59:44,309] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=save_data_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-12T03:06:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-12T03:06:00+00:00
[2022-06-12 16:59:44,329] {python.py:173} INFO - Done. Returned value was: None
[2022-06-12 16:59:44,361] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=save_data_task, execution_date=20220612T030600, start_date=20220612T145943, end_date=20220612T145944
[2022-06-12 16:59:44,471] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-12 16:59:44,638] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
