[2022-06-12 16:18:55,477] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.save_data_task scheduled__2022-06-11T23:13:00+00:00 [queued]>
[2022-06-12 16:18:55,503] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.save_data_task scheduled__2022-06-11T23:13:00+00:00 [queued]>
[2022-06-12 16:18:55,504] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 16:18:55,504] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-12 16:18:55,505] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 16:18:55,565] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): save_data_task> on 2022-06-11 23:13:00+00:00
[2022-06-12 16:18:55,582] {standard_task_runner.py:52} INFO - Started process 3013 to run task
[2022-06-12 16:18:55,586] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_data', 'save_data_task', 'scheduled__2022-06-11T23:13:00+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpwl25agsy', '--error-file', '/tmp/tmpvws6my2t']
[2022-06-12 16:18:55,588] {standard_task_runner.py:80} INFO - Job 301: Subtask save_data_task
[2022-06-12 16:18:55,732] {task_command.py:370} INFO - Running <TaskInstance: ingest_data.save_data_task scheduled__2022-06-11T23:13:00+00:00 [running]> on host DESKTOP-GDPK8BL.localdomain
[2022-06-12 16:18:56,139] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=save_data_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-11T23:13:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-11T23:13:00+00:00
[2022-06-12 16:18:56,154] {python.py:173} INFO - Done. Returned value was: None
[2022-06-12 16:18:56,183] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=save_data_task, execution_date=20220611T231300, start_date=20220612T141855, end_date=20220612T141856
[2022-06-12 16:18:56,288] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-12 16:18:56,470] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
