[2022-06-12 17:00:36,384] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.save_data_task scheduled__2022-06-12T03:11:00+00:00 [queued]>
[2022-06-12 17:00:36,434] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.save_data_task scheduled__2022-06-12T03:11:00+00:00 [queued]>
[2022-06-12 17:00:36,434] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 17:00:36,435] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-12 17:00:36,436] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 17:00:36,513] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): save_data_task> on 2022-06-12 03:11:00+00:00
[2022-06-12 17:00:36,521] {standard_task_runner.py:52} INFO - Started process 6606 to run task
[2022-06-12 17:00:36,527] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_data', 'save_data_task', 'scheduled__2022-06-12T03:11:00+00:00', '--job-id', '778', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpx84tzqij', '--error-file', '/tmp/tmp_ywzw_p4']
[2022-06-12 17:00:36,529] {standard_task_runner.py:80} INFO - Job 778: Subtask save_data_task
[2022-06-12 17:00:36,682] {task_command.py:370} INFO - Running <TaskInstance: ingest_data.save_data_task scheduled__2022-06-12T03:11:00+00:00 [running]> on host DESKTOP-GDPK8BL.localdomain
[2022-06-12 17:00:37,147] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=save_data_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-12T03:11:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-12T03:11:00+00:00
[2022-06-12 17:00:37,162] {python.py:173} INFO - Done. Returned value was: None
[2022-06-12 17:00:37,185] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=save_data_task, execution_date=20220612T031100, start_date=20220612T150036, end_date=20220612T150037
[2022-06-12 17:00:37,267] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-12 17:00:37,447] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
