[2022-06-12 19:43:54,954] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.save_data_task scheduled__2022-06-12T08:38:00+00:00 [queued]>
[2022-06-12 19:43:54,993] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.save_data_task scheduled__2022-06-12T08:38:00+00:00 [queued]>
[2022-06-12 19:43:54,993] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 19:43:54,994] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-12 19:43:54,994] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 19:43:55,069] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): save_data_task> on 2022-06-12 08:38:00+00:00
[2022-06-12 19:43:55,075] {standard_task_runner.py:52} INFO - Started process 11450 to run task
[2022-06-12 19:43:55,085] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_data', 'save_data_task', 'scheduled__2022-06-12T08:38:00+00:00', '--job-id', '1432', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpb65ii1tf', '--error-file', '/tmp/tmpb8hwuujj']
[2022-06-12 19:43:55,090] {standard_task_runner.py:80} INFO - Job 1432: Subtask save_data_task
[2022-06-12 19:43:55,235] {task_command.py:370} INFO - Running <TaskInstance: ingest_data.save_data_task scheduled__2022-06-12T08:38:00+00:00 [running]> on host DESKTOP-GDPK8BL.localdomain
[2022-06-12 19:43:55,834] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=save_data_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-12T08:38:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-12T08:38:00+00:00
[2022-06-12 19:43:55,850] {python.py:173} INFO - Done. Returned value was: None
[2022-06-12 19:43:55,880] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=save_data_task, execution_date=20220612T083800, start_date=20220612T174354, end_date=20220612T174355
[2022-06-12 19:43:55,985] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-12 19:43:56,195] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
